apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9100'
  
spec:
  selector: 
    k8s-app: node-exporter
  type: ClusterIP
  ports:
    - port: 9100
      targetPort: 9100

