---
- name: Install libpam-cracklib
  package:
    name: "libpam-cracklib"
    state: present

- name: Configure libpam-cracklib
  lineinfile:
    dest: "/etc/pam.d/common-password"
    regexp: "pam_cracklib.so"
    line: "password required pam_cracklib.so try_first_pass retry=3 minlen=12 dcredit=-1 ucredit=-1 ocredit=-1 lcredit=-1 enforce_for_root"
    state: present

- name: Limit Password Reuse
  lineinfile:
    dest: "/etc/pam.d/common-password"
    regexp: "remember=5"
    line: "password sufficient pam_unix.so remember=5"
    state: present


