apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: drone-agent
spec:
    selector:
        matchLabels:
            app: drone-agent
    replicas: 1
    template:
        metadata:
            labels:
                app: drone-agent
        spec:
            containers:
              - name: drone-agent
                image: drone/agent:1.0.0
                args: ["agent"]
                env:
                  - name: DRONE_SERVER
                    value: "drone:3000"
                  - name: DRONE_SECRET
                    value: "0087823e97a406be528c08bc9b04d6b3"
                volumeMounts:
                  - mountPath: /var/run/docker.sock
                    name: docker-socket
            volumes:
              - name: docker-socket
                hostPath:
                    path: /var/run/docker.sock
