apiVersion: v1
kind: Pod
metadata:
  name: drone
  labels:
    app: drone
spec:
  serviceAccountName: drone-rbac
  containers:
  - name: drone
    image: drone/drone:1.0.0
    env:
    - name: DRONE_LOGS_DEBUG
      value: "true"
    - name: DRONE_KUBERNETES_ENABLED
      value: "true"
    - name: DRONE_KUBERNETES_NAMESPACE
      value: "default"
    - name: DRONE_GITEA_SERVER
      value: "http://gitea-gitea-http:3000"
    - name: DRONE_RPC_SECRET
      value: "0087823e97a406be528c08bc9b04d6b3"
    - name: DRONE_SERVER_HOST
      value: "drone"
    - name: DRONE_SERVER_PROTO
      value: "http"
    ports:
      - containerPort: 80
      - containerPort: 443
