apiVersion: skaffold/v2beta14
kind: Config
build:
  local: {}
  artifacts:
  - image: dftd/telnet-server
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
        - .
test:
- image: dftd/telnet-server
  structureTests:
  - ./container-tests/*

deploy:
  kubectl:
    manifests:
    - kubernetes/*
