---
- set_fact:
    greeting_application_file: "/opt/engineering/greeting.py"

- name: Create Sudoers file for developers group
  template:
    src: "../ansible/templates/developers.j2"
    dest: "/etc/sudoers.d/developers"
    validate: 'visudo -cf %s'
